version: '3.1'

services:
  stats-server:
    build: stats/server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=stats

  stats-db:
    image: postgres:15.1-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=stats

  ewm-service:
    build: ewm_service
    image: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"

#  ewm-db:
#    image: postgres:14-alpine
